server:
  port: 8191
spring:
  cloud: 
    config:
      server:
        git:
          uri: https://github.com/YuvasekharReddy/spring-cloud-config-store
          search-paths:
           - '*service'
